name: Build and Release APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'  # أو أحدث إصدار مستقر
          channel: 'stable'
          cache: true
      
      - name: Flutter Doctor
        run: flutter doctor -v
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Run code generation
        run: flutter pub run build_runner build --delete-conflicting-outputs
      
      - name: Analyze code
        run: flutter analyze
        continue-on-error: true
      
      - name: Build APK (Debug)
        if: github.event_name == 'pull_request'
        run: flutter build apk --debug
      
      - name: Build APK (Release)
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: flutter build apk --release
      
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mulaazim-apk-${{ github.run_number }}
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
          retention-days: 30
      
      - name: Get APK Info
        if: success()
        run: |
          echo "APK Size: $(du -h build/app/outputs/flutter-apk/app-release.apk | cut -f1)"
          echo "APK Path: build/app/outputs/flutter-apk/app-release.apk"
